# Perform the EOS interface tasks under Ansible 2.1 or earlier
# using the Ansible eos_template module
- name: Arista EOS interface resources (Ansible <= 2.1)
  eos_template:
    src: interface.j2
    include_defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  when: item.name is defined
  with_items: "{{ interfaces | default([]) }}"
