# Perform the EOS interface tasks under Ansible 2.2 or later
# using the Ansible eos_config module
- name: Arista EOS interface resources (Ansible >= 2.2)
  eos_config:
    src: interface.j2
    defaults: true
    config: "{{ _eos_config | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
  notify: save running config
  when: item.name is defined
  with_items: "{{ interfaces | default([]) }}"
